{"uid":"7acab80f3eb9ca7f","name":"test_smoke","fullName":"tests.integration.test_smoke#test_smoke","historyId":"78ffebf457376473b3476ee0f7a454c9","time":{"start":1753925149370,"stop":1753926364422,"duration":1215052},"description":"Deploy bundle with apps and test various component integrations.","descriptionHtml":"<p>Deploy bundle with apps and test various component integrations.</p>\n","status":"broken","statusMessage":"TimeoutError","statusTrace":"Traceback (most recent call last):\n  File \"/usr/lib/python3.12/asyncio/tasks.py\", line 520, in wait_for\n    return await fut\n           ^^^^^^^^^\n  File \"/home/runner/work/mysql-k8s-bundle/mysql-k8s-bundle/.tox/integration/lib/python3.12/site-packages/juju/utils.py\", line 129, in _block\n    await jasyncio.sleep(wait_period)\n  File \"/usr/lib/python3.12/asyncio/tasks.py\", line 665, in sleep\n    return await future\n           ^^^^^^^^^^^^\nasyncio.exceptions.CancelledError\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"/home/runner/work/mysql-k8s-bundle/mysql-k8s-bundle/.tox/integration/lib/python3.12/site-packages/_pytest/runner.py\", line 341, in from_call\n    result: TResult | None = func()\n                             ^^^^^^\n  File \"/home/runner/work/mysql-k8s-bundle/mysql-k8s-bundle/.tox/integration/lib/python3.12/site-packages/_pytest/runner.py\", line 242, in <lambda>\n    lambda: runtest_hook(item=item, **kwds), when=when, reraise=reraise\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/work/mysql-k8s-bundle/mysql-k8s-bundle/.tox/integration/lib/python3.12/site-packages/pluggy/_hooks.py\", line 513, in __call__\n    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/work/mysql-k8s-bundle/mysql-k8s-bundle/.tox/integration/lib/python3.12/site-packages/pluggy/_manager.py\", line 120, in _hookexec\n    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/work/mysql-k8s-bundle/mysql-k8s-bundle/.tox/integration/lib/python3.12/site-packages/pluggy/_callers.py\", line 182, in _multicall\n    return outcome.get_result()\n           ^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/work/mysql-k8s-bundle/mysql-k8s-bundle/.tox/integration/lib/python3.12/site-packages/pluggy/_result.py\", line 100, in get_result\n    raise exc.with_traceback(exc.__traceback__)\n  File \"/home/runner/work/mysql-k8s-bundle/mysql-k8s-bundle/.tox/integration/lib/python3.12/site-packages/pluggy/_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"/home/runner/work/mysql-k8s-bundle/mysql-k8s-bundle/.tox/integration/lib/python3.12/site-packages/_pytest/threadexception.py\", line 92, in pytest_runtest_call\n    yield from thread_exception_runtest_hook()\n  File \"/home/runner/work/mysql-k8s-bundle/mysql-k8s-bundle/.tox/integration/lib/python3.12/site-packages/_pytest/threadexception.py\", line 68, in thread_exception_runtest_hook\n    yield\n  File \"/home/runner/work/mysql-k8s-bundle/mysql-k8s-bundle/.tox/integration/lib/python3.12/site-packages/pluggy/_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"/home/runner/work/mysql-k8s-bundle/mysql-k8s-bundle/.tox/integration/lib/python3.12/site-packages/_pytest/unraisableexception.py\", line 95, in pytest_runtest_call\n    yield from unraisable_exception_runtest_hook()\n  File \"/home/runner/work/mysql-k8s-bundle/mysql-k8s-bundle/.tox/integration/lib/python3.12/site-packages/_pytest/unraisableexception.py\", line 70, in unraisable_exception_runtest_hook\n    yield\n  File \"/home/runner/work/mysql-k8s-bundle/mysql-k8s-bundle/.tox/integration/lib/python3.12/site-packages/pluggy/_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"/home/runner/work/mysql-k8s-bundle/mysql-k8s-bundle/.tox/integration/lib/python3.12/site-packages/_pytest/logging.py\", line 846, in pytest_runtest_call\n    yield from self._runtest_for(item, \"call\")\n  File \"/home/runner/work/mysql-k8s-bundle/mysql-k8s-bundle/.tox/integration/lib/python3.12/site-packages/_pytest/logging.py\", line 829, in _runtest_for\n    yield\n  File \"/home/runner/work/mysql-k8s-bundle/mysql-k8s-bundle/.tox/integration/lib/python3.12/site-packages/pluggy/_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"/home/runner/work/mysql-k8s-bundle/mysql-k8s-bundle/.tox/integration/lib/python3.12/site-packages/_pytest/capture.py\", line 880, in pytest_runtest_call\n    return (yield)\n            ^^^^^\n  File \"/home/runner/work/mysql-k8s-bundle/mysql-k8s-bundle/.tox/integration/lib/python3.12/site-packages/pluggy/_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"/home/runner/work/mysql-k8s-bundle/mysql-k8s-bundle/.tox/integration/lib/python3.12/site-packages/_pytest/skipping.py\", line 257, in pytest_runtest_call\n    return (yield)\n            ^^^^^\n  File \"/home/runner/work/mysql-k8s-bundle/mysql-k8s-bundle/.tox/integration/lib/python3.12/site-packages/pluggy/_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/work/mysql-k8s-bundle/mysql-k8s-bundle/.tox/integration/lib/python3.12/site-packages/_pytest/runner.py\", line 174, in pytest_runtest_call\n    item.runtest()\n  File \"/home/runner/work/mysql-k8s-bundle/mysql-k8s-bundle/.tox/integration/lib/python3.12/site-packages/_pytest/python.py\", line 1627, in runtest\n    self.ihook.pytest_pyfunc_call(pyfuncitem=self)\n  File \"/home/runner/work/mysql-k8s-bundle/mysql-k8s-bundle/.tox/integration/lib/python3.12/site-packages/pluggy/_hooks.py\", line 513, in __call__\n    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/work/mysql-k8s-bundle/mysql-k8s-bundle/.tox/integration/lib/python3.12/site-packages/pluggy/_manager.py\", line 120, in _hookexec\n    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/work/mysql-k8s-bundle/mysql-k8s-bundle/.tox/integration/lib/python3.12/site-packages/pluggy/_callers.py\", line 182, in _multicall\n    return outcome.get_result()\n           ^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/work/mysql-k8s-bundle/mysql-k8s-bundle/.tox/integration/lib/python3.12/site-packages/pluggy/_result.py\", line 100, in get_result\n    raise exc.with_traceback(exc.__traceback__)\n  File \"/home/runner/work/mysql-k8s-bundle/mysql-k8s-bundle/.tox/integration/lib/python3.12/site-packages/pluggy/_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/work/mysql-k8s-bundle/mysql-k8s-bundle/.tox/integration/lib/python3.12/site-packages/_pytest/python.py\", line 159, in pytest_pyfunc_call\n    result = testfunction(**testargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/work/mysql-k8s-bundle/mysql-k8s-bundle/.tox/integration/lib/python3.12/site-packages/pytest_asyncio/plugin.py\", line 529, in inner\n    _loop.run_until_complete(task)\n  File \"/usr/lib/python3.12/asyncio/base_events.py\", line 687, in run_until_complete\n    return future.result()\n           ^^^^^^^^^^^^^^^\n  File \"/home/runner/work/mysql-k8s-bundle/mysql-k8s-bundle/tests/integration/test_smoke.py\", line 68, in test_smoke\n    await ensure_statuses(ops_test)\n  File \"/home/runner/work/mysql-k8s-bundle/mysql-k8s-bundle/tests/integration/test_smoke.py\", line 40, in ensure_statuses\n    await ops_test.model.block_until(\n  File \"/home/runner/work/mysql-k8s-bundle/mysql-k8s-bundle/.tox/integration/lib/python3.12/site-packages/juju/model.py\", line 1046, in block_until\n    await utils.block_until(done,\n  File \"/home/runner/work/mysql-k8s-bundle/mysql-k8s-bundle/.tox/integration/lib/python3.12/site-packages/juju/utils.py\", line 130, in block_until\n    await jasyncio.shield(jasyncio.wait_for(_block(), timeout))\n  File \"/usr/lib/python3.12/asyncio/tasks.py\", line 519, in wait_for\n    async with timeouts.timeout(timeout):\n  File \"/usr/lib/python3.12/asyncio/timeouts.py\", line 115, in __aexit__\n    raise TimeoutError from exc_val\nTimeoutError","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":1,"retriesStatusChange":true,"beforeStages":[{"name":"event_loop","time":{"start":1753925149128,"stop":1753925149128,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"tmp_path_factory","time":{"start":1753925149128,"stop":1753925149128,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"ops_test","time":{"start":1753925149128,"stop":1753925149369,"duration":241},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"abort_on_fail","time":{"start":1753925149370,"stop":1753925149370,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false}],"testStage":{"description":"Deploy bundle with apps and test various component integrations.","status":"broken","statusMessage":"TimeoutError","statusTrace":"Traceback (most recent call last):\n  File \"/usr/lib/python3.12/asyncio/tasks.py\", line 520, in wait_for\n    return await fut\n           ^^^^^^^^^\n  File \"/home/runner/work/mysql-k8s-bundle/mysql-k8s-bundle/.tox/integration/lib/python3.12/site-packages/juju/utils.py\", line 129, in _block\n    await jasyncio.sleep(wait_period)\n  File \"/usr/lib/python3.12/asyncio/tasks.py\", line 665, in sleep\n    return await future\n           ^^^^^^^^^^^^\nasyncio.exceptions.CancelledError\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"/home/runner/work/mysql-k8s-bundle/mysql-k8s-bundle/.tox/integration/lib/python3.12/site-packages/_pytest/runner.py\", line 341, in from_call\n    result: TResult | None = func()\n                             ^^^^^^\n  File \"/home/runner/work/mysql-k8s-bundle/mysql-k8s-bundle/.tox/integration/lib/python3.12/site-packages/_pytest/runner.py\", line 242, in <lambda>\n    lambda: runtest_hook(item=item, **kwds), when=when, reraise=reraise\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/work/mysql-k8s-bundle/mysql-k8s-bundle/.tox/integration/lib/python3.12/site-packages/pluggy/_hooks.py\", line 513, in __call__\n    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/work/mysql-k8s-bundle/mysql-k8s-bundle/.tox/integration/lib/python3.12/site-packages/pluggy/_manager.py\", line 120, in _hookexec\n    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/work/mysql-k8s-bundle/mysql-k8s-bundle/.tox/integration/lib/python3.12/site-packages/pluggy/_callers.py\", line 182, in _multicall\n    return outcome.get_result()\n           ^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/work/mysql-k8s-bundle/mysql-k8s-bundle/.tox/integration/lib/python3.12/site-packages/pluggy/_result.py\", line 100, in get_result\n    raise exc.with_traceback(exc.__traceback__)\n  File \"/home/runner/work/mysql-k8s-bundle/mysql-k8s-bundle/.tox/integration/lib/python3.12/site-packages/pluggy/_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"/home/runner/work/mysql-k8s-bundle/mysql-k8s-bundle/.tox/integration/lib/python3.12/site-packages/_pytest/threadexception.py\", line 92, in pytest_runtest_call\n    yield from thread_exception_runtest_hook()\n  File \"/home/runner/work/mysql-k8s-bundle/mysql-k8s-bundle/.tox/integration/lib/python3.12/site-packages/_pytest/threadexception.py\", line 68, in thread_exception_runtest_hook\n    yield\n  File \"/home/runner/work/mysql-k8s-bundle/mysql-k8s-bundle/.tox/integration/lib/python3.12/site-packages/pluggy/_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"/home/runner/work/mysql-k8s-bundle/mysql-k8s-bundle/.tox/integration/lib/python3.12/site-packages/_pytest/unraisableexception.py\", line 95, in pytest_runtest_call\n    yield from unraisable_exception_runtest_hook()\n  File \"/home/runner/work/mysql-k8s-bundle/mysql-k8s-bundle/.tox/integration/lib/python3.12/site-packages/_pytest/unraisableexception.py\", line 70, in unraisable_exception_runtest_hook\n    yield\n  File \"/home/runner/work/mysql-k8s-bundle/mysql-k8s-bundle/.tox/integration/lib/python3.12/site-packages/pluggy/_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"/home/runner/work/mysql-k8s-bundle/mysql-k8s-bundle/.tox/integration/lib/python3.12/site-packages/_pytest/logging.py\", line 846, in pytest_runtest_call\n    yield from self._runtest_for(item, \"call\")\n  File \"/home/runner/work/mysql-k8s-bundle/mysql-k8s-bundle/.tox/integration/lib/python3.12/site-packages/_pytest/logging.py\", line 829, in _runtest_for\n    yield\n  File \"/home/runner/work/mysql-k8s-bundle/mysql-k8s-bundle/.tox/integration/lib/python3.12/site-packages/pluggy/_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"/home/runner/work/mysql-k8s-bundle/mysql-k8s-bundle/.tox/integration/lib/python3.12/site-packages/_pytest/capture.py\", line 880, in pytest_runtest_call\n    return (yield)\n            ^^^^^\n  File \"/home/runner/work/mysql-k8s-bundle/mysql-k8s-bundle/.tox/integration/lib/python3.12/site-packages/pluggy/_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"/home/runner/work/mysql-k8s-bundle/mysql-k8s-bundle/.tox/integration/lib/python3.12/site-packages/_pytest/skipping.py\", line 257, in pytest_runtest_call\n    return (yield)\n            ^^^^^\n  File \"/home/runner/work/mysql-k8s-bundle/mysql-k8s-bundle/.tox/integration/lib/python3.12/site-packages/pluggy/_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/work/mysql-k8s-bundle/mysql-k8s-bundle/.tox/integration/lib/python3.12/site-packages/_pytest/runner.py\", line 174, in pytest_runtest_call\n    item.runtest()\n  File \"/home/runner/work/mysql-k8s-bundle/mysql-k8s-bundle/.tox/integration/lib/python3.12/site-packages/_pytest/python.py\", line 1627, in runtest\n    self.ihook.pytest_pyfunc_call(pyfuncitem=self)\n  File \"/home/runner/work/mysql-k8s-bundle/mysql-k8s-bundle/.tox/integration/lib/python3.12/site-packages/pluggy/_hooks.py\", line 513, in __call__\n    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/work/mysql-k8s-bundle/mysql-k8s-bundle/.tox/integration/lib/python3.12/site-packages/pluggy/_manager.py\", line 120, in _hookexec\n    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/work/mysql-k8s-bundle/mysql-k8s-bundle/.tox/integration/lib/python3.12/site-packages/pluggy/_callers.py\", line 182, in _multicall\n    return outcome.get_result()\n           ^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/work/mysql-k8s-bundle/mysql-k8s-bundle/.tox/integration/lib/python3.12/site-packages/pluggy/_result.py\", line 100, in get_result\n    raise exc.with_traceback(exc.__traceback__)\n  File \"/home/runner/work/mysql-k8s-bundle/mysql-k8s-bundle/.tox/integration/lib/python3.12/site-packages/pluggy/_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/work/mysql-k8s-bundle/mysql-k8s-bundle/.tox/integration/lib/python3.12/site-packages/_pytest/python.py\", line 159, in pytest_pyfunc_call\n    result = testfunction(**testargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/work/mysql-k8s-bundle/mysql-k8s-bundle/.tox/integration/lib/python3.12/site-packages/pytest_asyncio/plugin.py\", line 529, in inner\n    _loop.run_until_complete(task)\n  File \"/usr/lib/python3.12/asyncio/base_events.py\", line 687, in run_until_complete\n    return future.result()\n           ^^^^^^^^^^^^^^^\n  File \"/home/runner/work/mysql-k8s-bundle/mysql-k8s-bundle/tests/integration/test_smoke.py\", line 68, in test_smoke\n    await ensure_statuses(ops_test)\n  File \"/home/runner/work/mysql-k8s-bundle/mysql-k8s-bundle/tests/integration/test_smoke.py\", line 40, in ensure_statuses\n    await ops_test.model.block_until(\n  File \"/home/runner/work/mysql-k8s-bundle/mysql-k8s-bundle/.tox/integration/lib/python3.12/site-packages/juju/model.py\", line 1046, in block_until\n    await utils.block_until(done,\n  File \"/home/runner/work/mysql-k8s-bundle/mysql-k8s-bundle/.tox/integration/lib/python3.12/site-packages/juju/utils.py\", line 130, in block_until\n    await jasyncio.shield(jasyncio.wait_for(_block(), timeout))\n  File \"/usr/lib/python3.12/asyncio/tasks.py\", line 519, in wait_for\n    async with timeouts.timeout(timeout):\n  File \"/usr/lib/python3.12/asyncio/timeouts.py\", line 115, in __aexit__\n    raise TimeoutError from exc_val\nTimeoutError","steps":[],"attachments":[{"uid":"2c74c2baa9e3228a","name":"log","source":"2c74c2baa9e3228a.txt","type":"text/plain","size":73766}],"parameters":[],"shouldDisplayMessage":true,"stepsCount":0,"attachmentsCount":1,"hasContent":true,"attachmentStep":false},"afterStages":[{"name":"ops_test::finalizer","time":{"start":1753926364555,"stop":1753926364972,"duration":417},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"abort_on_fail::0","time":{"start":1753926364555,"stop":1753926364555,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"event_loop::2","time":{"start":1753926364973,"stop":1753926364973,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"event_loop::_close_event_loop","time":{"start":1753926364973,"stop":1753926364973,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"event_loop::_provide_clean_event_loop","time":{"start":1753926364973,"stop":1753926364973,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false}],"labels":[{"name":"tag","value":"group(1)"},{"name":"tag","value":"abort_on_fail"},{"name":"tag","value":"asyncio"},{"name":"parentSuite","value":"tests.integration"},{"name":"suite","value":"test_smoke"},{"name":"host","value":"pkrvmjbmru5nbw0"},{"name":"thread","value":"15971-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"tests.integration.test_smoke"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[{"uid":"e8892c06a95fdcd7","status":"unknown","time":{}}],"categories":[{"name":"Test defects","matchedStatuses":[]}],"history":{"statistic":{"failed":34,"broken":154,"skipped":0,"passed":165,"unknown":8,"total":361},"items":[{"uid":"8e902dce4f346ee6","reportUrl":"../1966//#testresult/8e902dce4f346ee6","status":"broken","statusDetails":"TimeoutError","time":{"start":1753838781294,"stop":1753839996373,"duration":1215079}},{"uid":"cd7a03fd2bd9ce7f","reportUrl":"../1962//#testresult/cd7a03fd2bd9ce7f","status":"broken","statusDetails":"TimeoutError","time":{"start":1753752417742,"stop":1753753632541,"duration":1214799}},{"uid":"1e6f7fb3e90266d4","reportUrl":"../1961//#testresult/1e6f7fb3e90266d4","status":"broken","statusDetails":"TimeoutError","time":{"start":1753666018851,"stop":1753667236703,"duration":1217852}},{"uid":"20724f14e536817d","reportUrl":"../1960//#testresult/20724f14e536817d","status":"broken","statusDetails":"TimeoutError","time":{"start":1753579620633,"stop":1753580838320,"duration":1217687}},{"uid":"e0c53424b75aaba0","reportUrl":"../1959//#testresult/e0c53424b75aaba0","status":"broken","statusDetails":"TimeoutError","time":{"start":1753493263372,"stop":1753494708668,"duration":1445296}},{"uid":"ca67bc5837bf39b5","reportUrl":"../1958//#testresult/ca67bc5837bf39b5","status":"broken","statusDetails":"TimeoutError","time":{"start":1753406753908,"stop":1753407971641,"duration":1217733}},{"uid":"39345d8151d32955","reportUrl":"../1957//#testresult/39345d8151d32955","status":"broken","statusDetails":"TimeoutError","time":{"start":1753320412129,"stop":1753321629384,"duration":1217255}},{"uid":"16546e9416cd2974","reportUrl":"../1956//#testresult/16546e9416cd2974","status":"broken","statusDetails":"TimeoutError","time":{"start":1753233984192,"stop":1753235198267,"duration":1214075}},{"uid":"d9f9b1204c9db599","reportUrl":"../1954//#testresult/d9f9b1204c9db599","status":"passed","time":{"start":1753147655290,"stop":1753148077108,"duration":421818}},{"uid":"b9c11d1ad2b6bd74","reportUrl":"../1953//#testresult/b9c11d1ad2b6bd74","status":"broken","statusDetails":"TimeoutError","time":{"start":1753061241522,"stop":1753062454684,"duration":1213162}},{"uid":"7d6f1a852437bc8b","reportUrl":"../1952//#testresult/7d6f1a852437bc8b","status":"broken","statusDetails":"TimeoutError","time":{"start":1752974814333,"stop":1752976027196,"duration":1212863}},{"uid":"d09cade44fedad53","reportUrl":"../1951//#testresult/d09cade44fedad53","status":"broken","statusDetails":"TimeoutError","time":{"start":1752888320444,"stop":1752889532922,"duration":1212478}},{"uid":"673272a8ac13ce99","reportUrl":"../1950//#testresult/673272a8ac13ce99","status":"broken","statusDetails":"TimeoutError","time":{"start":1752801926272,"stop":1752803139180,"duration":1212908}},{"uid":"5acacd7380e696ba","reportUrl":"../1949//#testresult/5acacd7380e696ba","status":"broken","statusDetails":"TimeoutError","time":{"start":1752715529711,"stop":1752716742670,"duration":1212959}},{"uid":"3f4bf851a88aed8f","reportUrl":"../1948//#testresult/3f4bf851a88aed8f","status":"broken","statusDetails":"TimeoutError","time":{"start":1752629138226,"stop":1752630350894,"duration":1212668}},{"uid":"f3eb504e333b51e1","reportUrl":"../1947//#testresult/f3eb504e333b51e1","status":"broken","statusDetails":"TimeoutError","time":{"start":1752542730700,"stop":1752543943117,"duration":1212417}},{"uid":"cb6541cb0de52137","reportUrl":"../1945//#testresult/cb6541cb0de52137","status":"broken","statusDetails":"TimeoutError","time":{"start":1752456504164,"stop":1752457721212,"duration":1217048}},{"uid":"b71d24da1fe7dfd0","reportUrl":"../1944//#testresult/b71d24da1fe7dfd0","status":"broken","statusDetails":"TimeoutError","time":{"start":1752370036596,"stop":1752371252200,"duration":1215604}},{"uid":"99323ae0da684be3","reportUrl":"../1943//#testresult/99323ae0da684be3","status":"broken","statusDetails":"TimeoutError","time":{"start":1752283593241,"stop":1752284806224,"duration":1212983}},{"uid":"3e534f89c9c14f64","reportUrl":"../1942//#testresult/3e534f89c9c14f64","status":"broken","statusDetails":"TimeoutError","time":{"start":1752197175543,"stop":1752198389457,"duration":1213914}}]},"tags":["asyncio","abort_on_fail","group(1)"]},"source":"7acab80f3eb9ca7f.json","parameterValues":[]}